"""Create table

Revision ID: 4c18b017a7d5
Revises: 
Create Date: 2024-11-27 15:06:11.662397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c18b017a7d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_balance', sa.Float(), nullable=True),
    sa.Column('food', sa.Float(), nullable=True),
    sa.Column('house_hold', sa.Float(), nullable=True),
    sa.Column('clothing', sa.Float(), nullable=True),
    sa.Column('personal_expense', sa.Float(), nullable=True),
    sa.Column('subscription', sa.Float(), nullable=True),
    sa.Column('housing_expense', sa.Float(), nullable=True),
    sa.Column('insurance', sa.Float(), nullable=True),
    sa.Column('other', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense')
    op.drop_table('user')
    # ### end Alembic commands ###
